export const colors = {
    black: '#000',
    white: '#FFF',
    themeBackground: '#F7F7F7',
    fontMainColor: '#212121',
    fontSecondColor: '#4A4A4A',
    fontBlue: '#6178DE',
    iconColor: '#F48B98',
    horizontalLine: '#949393',
    lightHorizontalLine: '#f0f0f0',
    spinnerColor: '#F48B98',

    blackText: '#4A4A4A',
    whiteColor: '#fff',
    brownColor: '#D0AD8A',
    facebookBlueColor: '#3B5998',
    googleRedColor: '#DC4E41',
    blueColor: '#2962FF',
    secondaryWhiteColor: '#fff',
    greenColor: '#8CB65E',
    lightBlueColor: '#6178DE',
    pinkColor: '#F48B98',
    textBlueColor: '#6178DE',
    greenTextColor: '#8CB65E',
    // many shades of gray
    backgroudGray: '#F7F7F7',
    darkGrayText: '#9B9B9B',
    grayLinesColor: '#EAEAEA',
};
